### ISSUE TITLE
Implement Teacher & Student User Models

### ISSUE THREAD

**Issue by vishesh147** [MSTC-DA-IICT/Hacktoberfest22-E-Learn-App-Django#2]
You need to create Teacher and Student user models using User as a Foreign Key.

Both models must include:
1.  Joining Date
2.  Unique Student ID

**Comment by mugdha273** [comment]
Hey @vishesh147 please assign me this issue

**Comment by vishesh147** [comment]
Sure I'll assign it to you! @mugdha273

**Comment by vishesh147** [comment]
Looks good! For changes to the models new Issues will be created as required.
