### ISSUE TITLE
Create Landing Page 

### ISSUE THREAD

**Issue by vishesh147** [MSTC-DA-IICT/Hacktoberfest22-E-Learn-App-Django#3]
Create a landing page with the following options:
1. Register New User
2. Login As Student
3. Login As Teacher

Must be implemented using HTML, CSS, Javascript. Use of Bootstrap is encouraged.

**Comment by ykodwani01** [comment]
I would like to work on this issue .
Below is one of the similar page that I have worked upon in past
![frontend](https://user-images.githubusercontent.com/94884744/194390997-a83ee2dc-4be2-4d00-8425-004103c04391.JPG)

**Comment by PicantaData** [comment]
Go Ahead! Remember to include a navbar and the above-mentioned functionalities.
Note that making a registration form (as illustrated in your attached webpage image) is another issue.
